//! Grok Build **agent serve** process management for Settings → Runtime.
//!
//! CLI surface:
//! - `grok agent serve --bind <addr> --secret <token>`
//! - Default bind: `127.0.0.1:2419`
//! - Secret is auto-generated by the app and passed via `--secret` (never logged in full).
//!
//! Clients connect with:
//! - WebSocket URL: `ws://{bind}/ws?server-key={secret}`
//! - or CLI: `grok … --remote ws://{bind}/ws --secret <token>`

use std::net::{SocketAddr, TcpStream, ToSocketAddrs};
use std::path::Path;
use std::process::Stdio;
use std::sync::Mutex;
use std::time::Duration;

use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine};
use rand::RngCore;
use serde::{Deserialize, Serialize};

use crate::cli_probe;
use crate::process_util;
use crate::store;

const SERVE_START_WAIT_MS: u64 = 4000;
const SERVE_START_POLL_MS: u64 = 150;
/// Default listen address for `grok agent serve` (matches CLI default).
pub const DEFAULT_SERVE_BIND: &str = "127.0.0.1:2419";

/// Tracked PID of a serve process **we** spawned.
static TRACKED_SERVE: Mutex<Option<TrackedServe>> = Mutex::new(None);

#[derive(Debug, Clone)]
struct TrackedServe {
    pid: u32,
    pgid: Option<i32>,
    bind: String,
    /// Full secret — kept only in process memory for stop/status masking.
    secret: String,
}

/// Aggregate status for the Runtime panel (never includes the full secret).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ServeStatusDto {
    /// `stopped` | `running` | `error` | `unsupported`
    pub state: String,
    /// Bind address we use / last used (default `127.0.0.1:2419`).
    pub bind: String,
    /// Masked secret (`••••` + last 4) when we know it; never the full token.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub secret_masked: Option<String>,
    /// Last 4 chars of secret when known (for compact UI).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub secret_last4: Option<String>,
    /// Full connection URL — **only** returned from `serve_start` once.
    /// Subsequent `serve_status` omits this so secrets do not linger in status polls.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub connection_url: Option<String>,
    pub pid: Option<u64>,
    pub tracked_pid: Option<u64>,
    /// True when TCP connect to bind succeeds (best-effort).
    pub port_open: bool,
    pub cli_found: bool,
    pub cli_supports_serve: bool,
    pub message: Option<String>,
}

// ── Pure helpers (unit-tested) ──────────────────────────────────────────────

/// Mask secrets for UI / logs (never show full serve secret).
/// Same policy as leader: short values → all bullets; longer → bullets + last 4.
pub fn mask_secret(value: &str) -> String {
    let t = value.trim();
    if t.is_empty() {
        return String::new();
    }
    if t.len() <= 4 {
        return "••••".into();
    }
    let visible = t
        .chars()
        .rev()
        .take(4)
        .collect::<String>()
        .chars()
        .rev()
        .collect::<String>();
    format!("••••{visible}")
}

/// Last 4 characters of a secret (or empty / full if shorter).
pub fn secret_last4(value: &str) -> String {
    let t = value.trim();
    if t.is_empty() {
        return String::new();
    }
    t.chars()
        .rev()
        .take(4)
        .collect::<String>()
        .chars()
        .rev()
        .collect()
}

/// Cryptographic random secret (≥32 bytes, URL-safe base64, no padding).
pub fn generate_serve_secret() -> String {
    let mut bytes = [0u8; 32];
    rand::thread_rng().fill_bytes(&mut bytes);
    URL_SAFE_NO_PAD.encode(bytes)
}

/// Normalize / validate a bind string (`host:port`). Empty → default.
pub fn normalize_bind(bind: Option<&str>) -> Result<String, String> {
    let raw = bind.map(str::trim).filter(|s| !s.is_empty()).unwrap_or(DEFAULT_SERVE_BIND);
    // Reject whitespace and scheme prefixes so we only accept host:port.
    if raw.contains("://") || raw.contains('/') || raw.contains(' ') {
        return Err(format!("invalid serve bind (expected host:port): {raw}"));
    }
    // Must resolve to at least one socket addr.
    let addrs: Vec<SocketAddr> = raw
        .to_socket_addrs()
        .map_err(|e| format!("invalid serve bind `{raw}`: {e}"))?
        .collect();
    if addrs.is_empty() {
        return Err(format!("invalid serve bind `{raw}`: no addresses"));
    }
    Ok(raw.to_string())
}

/// Build the WebSocket connection URL clients use (`ws://{bind}/ws?server-key=…`).
pub fn build_connection_url(bind: &str, secret: &str) -> String {
    // Bind is host:port (possibly IPv6 in brackets already, or bare host:port).
    format!("ws://{bind}/ws?server-key={secret}")
}

/// Build a log-safe connection URL with masked secret query value.
pub fn build_connection_url_masked(bind: &str, secret: &str) -> String {
    format!("ws://{bind}/ws?server-key={}", mask_secret(secret))
}

/// Detect serve support from `grok agent serve --help` combined stdout/stderr.
pub fn parse_serve_help_supports(stdout: &str, stderr: &str, ok: bool) -> bool {
    if !ok {
        return false;
    }
    let blob = format!("{stdout}\n{stderr}").to_ascii_lowercase();
    // Fail closed: require both bind and secret surface.
    (blob.contains("--bind") || blob.contains("bind"))
        && (blob.contains("--secret") || blob.contains("secret"))
        && (blob.contains("websocket") || blob.contains("serve") || blob.contains("listen"))
}

/// Derive panel state from CLI capability + tracked process + port probe.
pub fn derive_serve_state(
    cli_found: bool,
    cli_supports_serve: bool,
    tracked_alive: bool,
    port_open: bool,
    support_msg: Option<&str>,
) -> (&'static str, Option<String>) {
    if !cli_found {
        return (
            "error",
            Some("Grok Build CLI not found. Install or set the CLI path under Runtime.".into()),
        );
    }
    if !cli_supports_serve {
        return (
            "unsupported",
            Some(
                support_msg
                    .unwrap_or(
                        "This Grok Build CLI version does not expose `agent serve` (WebSocket server).",
                    )
                    .to_string(),
            ),
        );
    }
    if tracked_alive || port_open {
        return ("running", None);
    }
    ("stopped", None)
}

// ── Process / CLI helpers ───────────────────────────────────────────────────

fn run_grok_cli_args(args: &[&str], timeout_secs: u64) -> Result<(String, String, bool), String> {
    let settings = store::load_settings();
    let probe = cli_probe::probe_cli(settings.manual_cli_path.as_deref());
    let Some(cli_path) = probe.path.filter(|_| probe.found) else {
        return Err("Grok Build CLI not found".into());
    };

    let args_owned: Vec<String> = args.iter().map(|s| (*s).to_string()).collect();
    let (tx, rx) = std::sync::mpsc::channel();
    std::thread::spawn(move || {
        let mut cmd = std::process::Command::new(&cli_path);
        cmd.args(&args_owned);
        process_util::apply_no_window_std(&mut cmd);
        if let Some(path_env) = process_util::enriched_path_env() {
            cmd.env("PATH", path_env);
        }
        let result = cmd.output();
        let _ = tx.send(result);
    });

    match rx.recv_timeout(Duration::from_secs(timeout_secs)) {
        Ok(Ok(output)) => {
            let stdout = String::from_utf8_lossy(&output.stdout).trim().to_string();
            let stderr = String::from_utf8_lossy(&output.stderr).trim().to_string();
            Ok((stdout, stderr, output.status.success()))
        }
        Ok(Err(e)) => Err(format!("Failed to run grok: {e}")),
        Err(_) => Err(format!("grok command timed out after {timeout_secs}s")),
    }
}

fn probe_cli_supports_serve() -> (bool, bool, Option<String>) {
    let settings = store::load_settings();
    let probe = cli_probe::probe_cli(settings.manual_cli_path.as_deref());
    if !probe.found {
        return (false, false, Some("Grok Build CLI not found".into()));
    }
    match run_grok_cli_args(&["agent", "serve", "--help"], 8) {
        Ok((stdout, stderr, ok)) => {
            let supports = parse_serve_help_supports(&stdout, &stderr, ok);
            if supports {
                (true, true, None)
            } else {
                (
                    true,
                    false,
                    Some(
                        "This Grok Build CLI version does not expose `agent serve` (WebSocket server)."
                            .into(),
                    ),
                )
            }
        }
        Err(e) => {
            if e.contains("not found") {
                (false, false, Some(e))
            } else {
                (true, false, Some(e))
            }
        }
    }
}

fn pid_alive(pid: u32) -> bool {
    #[cfg(unix)]
    {
        libc_kill(pid as i32, 0) == 0
    }
    #[cfg(windows)]
    {
        let out = std::process::Command::new("tasklist")
            .args(["/FI", &format!("PID eq {pid}"), "/NH"])
            .stdout(Stdio::piped())
            .stderr(Stdio::null())
            .output();
        match out {
            Ok(o) => {
                let s = String::from_utf8_lossy(&o.stdout);
                s.contains(&pid.to_string())
            }
            Err(_) => false,
        }
    }
}

fn kill_tracked(pid: u32, pgid: Option<i32>) {
    #[cfg(unix)]
    {
        if let Some(g) = pgid.or(Some(pid as i32)) {
            let _ = libc_kill(-g, 15); // SIGTERM group
            std::thread::sleep(Duration::from_millis(200));
            let _ = libc_kill(-g, 9);
            let _ = libc_waitpid(pid as i32);
            return;
        }
    }
    #[cfg(windows)]
    {
        let _ = pgid;
        let _ = std::process::Command::new("taskkill")
            .args(["/PID", &pid.to_string(), "/T", "/F"])
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status();
    }
}

#[cfg(unix)]
fn libc_kill(pid: i32, sig: i32) -> i32 {
    extern "C" {
        fn kill(pid: i32, sig: i32) -> i32;
    }
    unsafe { kill(pid, sig) }
}

#[cfg(unix)]
fn libc_setsid() -> i32 {
    extern "C" {
        fn setsid() -> i32;
    }
    unsafe { setsid() }
}

#[cfg(unix)]
fn libc_waitpid(pid: i32) -> i32 {
    extern "C" {
        fn waitpid(pid: i32, status: *mut i32, options: i32) -> i32;
    }
    // WNOHANG = 1
    unsafe { waitpid(pid, std::ptr::null_mut(), 1) }
}

fn clear_tracked_if_dead() {
    let mut guard = match TRACKED_SERVE.lock() {
        Ok(g) => g,
        Err(_) => return,
    };
    if let Some(t) = guard.as_ref() {
        if !pid_alive(t.pid) {
            *guard = None;
        }
    }
}

/// Best-effort TCP connect to bind (short timeout).
pub fn port_is_open(bind: &str) -> bool {
    let Ok(mut addrs) = bind.to_socket_addrs() else {
        return false;
    };
    let Some(addr) = addrs.next() else {
        return false;
    };
    TcpStream::connect_timeout(&addr, Duration::from_millis(200)).is_ok()
}

fn spawn_serve_process(
    cli_path: &Path,
    bind: &str,
    secret: &str,
) -> Result<TrackedServe, String> {
    // Never log full secret — only bind + masked.
    tracing::info!(
        target: "grok_app::serve",
        bind = %bind,
        secret = %mask_secret(secret),
        "spawning grok agent serve"
    );

    let mut cmd = std::process::Command::new(cli_path);
    cmd.arg("agent")
        .arg("serve")
        .arg("--bind")
        .arg(bind)
        .arg("--secret")
        .arg(secret)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null());

    process_util::apply_no_window_std(&mut cmd);
    if let Some(path_env) = process_util::enriched_path_env() {
        cmd.env("PATH", path_env);
    }
    // Prefer explicit secret over env bleed; clear accidental env secret pollution.
    cmd.env_remove("GROK_AGENT_SECRET");

    #[cfg(unix)]
    {
        use std::os::unix::process::CommandExt;
        // SAFETY: runs in child before exec; setsid → new session = process group.
        unsafe {
            cmd.pre_exec(|| {
                if libc_setsid() == -1 {
                    return Err(std::io::Error::last_os_error());
                }
                Ok(())
            });
        }
    }
    #[cfg(windows)]
    {
        use std::os::windows::process::CommandExt;
        const CREATE_NEW_PROCESS_GROUP: u32 = 0x0000_0200;
        const CREATE_NO_WINDOW: u32 = 0x0800_0000;
        cmd.creation_flags(CREATE_NEW_PROCESS_GROUP | CREATE_NO_WINDOW);
    }

    let mut child = cmd
        .spawn()
        .map_err(|e| format!("failed to spawn grok agent serve: {e}"))?;
    let pid = child.id();
    // Reap in background so we never leave zombies.
    std::thread::spawn(move || {
        let _ = child.wait();
    });

    Ok(TrackedServe {
        pid,
        pgid: Some(pid as i32),
        bind: bind.to_string(),
        secret: secret.to_string(),
    })
}

fn collect_status_sync(include_connection_url: bool) -> ServeStatusDto {
    clear_tracked_if_dead();

    let (cli_found, cli_supports_serve, support_msg) = probe_cli_supports_serve();

    let tracked = TRACKED_SERVE.lock().ok().and_then(|g| g.clone());
    let tracked_alive = tracked.as_ref().map(|t| pid_alive(t.pid)).unwrap_or(false);
    let bind = tracked
        .as_ref()
        .map(|t| t.bind.clone())
        .unwrap_or_else(|| DEFAULT_SERVE_BIND.to_string());
    let port_open = if cli_found && cli_supports_serve {
        port_is_open(&bind)
    } else {
        false
    };

    let (state, mut message) = derive_serve_state(
        cli_found,
        cli_supports_serve,
        tracked_alive,
        port_open,
        support_msg.as_deref(),
    );
    if message.is_none() {
        message = support_msg;
    }

    let (secret_masked, secret_last4_v, connection_url) = if let Some(ref t) = tracked {
        let masked = mask_secret(&t.secret);
        let last4 = secret_last4(&t.secret);
        let url = if include_connection_url {
            Some(build_connection_url(&t.bind, &t.secret))
        } else {
            None
        };
        (Some(masked), Some(last4), url)
    } else {
        (None, None, None)
    };

    // If port is open but we did not spawn serve, surface honest partial status.
    if state == "running" && tracked.is_none() && port_open {
        message = Some(format!(
            "Port {bind} is open (external serve or other process). Start/stop only manages processes started from this app."
        ));
    }

    ServeStatusDto {
        state: state.into(),
        bind,
        secret_masked,
        secret_last4: secret_last4_v,
        connection_url,
        pid: tracked.as_ref().map(|t| t.pid as u64),
        tracked_pid: tracked.as_ref().map(|t| t.pid as u64),
        port_open,
        cli_found,
        cli_supports_serve,
        message,
    }
}

// ── Tauri commands ──────────────────────────────────────────────────────────

/// Status for Settings → Runtime → Agent serve (secret always masked).
#[tauri::command]
pub async fn serve_status() -> Result<ServeStatusDto, String> {
    tauri::async_runtime::spawn_blocking(|| collect_status_sync(false))
        .await
        .map_err(|e| e.to_string())
}

/// Start `grok agent serve --bind --secret` (auto secret; default bind).
/// Returns status **including** one-time full `connectionUrl` for copy-to-clipboard.
#[tauri::command]
pub async fn serve_start(bind: Option<String>) -> Result<ServeStatusDto, String> {
    tauri::async_runtime::spawn_blocking(move || {
        let current = collect_status_sync(false);
        if current.state == "running" && current.tracked_pid.is_some() {
            // Already our process — re-issue connection URL for copy.
            return Ok(collect_status_sync(true));
        }
        if !current.cli_found {
            return Err("Grok Build CLI not found".into());
        }
        if !current.cli_supports_serve {
            return Err(current.message.unwrap_or_else(|| {
                "This CLI version cannot run `grok agent serve`".into()
            }));
        }

        // External process already on the default/requested port — fail closed rather
        // than double-bind and leak a secret for a process we do not control.
        let bind_norm = normalize_bind(bind.as_deref())?;
        if port_is_open(&bind_norm) && current.tracked_pid.is_none() {
            return Err(format!(
                "Port {bind_norm} is already in use. Stop the existing process or choose another bind."
            ));
        }

        let settings = store::load_settings();
        let probe = cli_probe::probe_cli(settings.manual_cli_path.as_deref());
        let Some(cli_path) = probe.path.filter(|_| probe.found) else {
            return Err("Grok Build CLI not found".into());
        };

        let secret = generate_serve_secret();
        // Log only masked form.
        tracing::info!(
            target: "grok_app::serve",
            bind = %bind_norm,
            secret = %mask_secret(&secret),
            url = %build_connection_url_masked(&bind_norm, &secret),
            "starting agent serve"
        );

        let tracked = spawn_serve_process(Path::new(&cli_path), &bind_norm, &secret)?;
        {
            let mut guard = TRACKED_SERVE
                .lock()
                .map_err(|_| "serve tracker lock poisoned".to_string())?;
            *guard = Some(tracked);
        }

        let deadline = std::time::Instant::now() + Duration::from_millis(SERVE_START_WAIT_MS);
        loop {
            if let Ok(g) = TRACKED_SERVE.lock() {
                if let Some(t) = g.as_ref() {
                    if !pid_alive(t.pid) {
                        drop(g);
                        let mut g2 = TRACKED_SERVE.lock().ok();
                        if let Some(ref mut gg) = g2 {
                            **gg = None;
                        }
                        return Err(
                            "Serve process exited immediately after start. Check CLI auth / logs."
                                .into(),
                        );
                    }
                }
            }
            if port_is_open(&bind_norm) {
                return Ok(collect_status_sync(true));
            }
            if std::time::Instant::now() >= deadline {
                // Process still alive — report running with connection URL for copy.
                let mut st = collect_status_sync(true);
                if st.state == "stopped" {
                    st.state = "running".into();
                    st.message = Some(
                        "Serve process spawned; waiting for port to become ready.".into(),
                    );
                }
                return Ok(st);
            }
            std::thread::sleep(Duration::from_millis(SERVE_START_POLL_MS));
        }
    })
    .await
    .map_err(|e| e.to_string())?
}

/// Stop the tracked `grok agent serve` process (app-spawned only).
#[tauri::command]
pub async fn serve_stop() -> Result<ServeStatusDto, String> {
    tauri::async_runtime::spawn_blocking(|| {
        if let Ok(mut guard) = TRACKED_SERVE.lock() {
            if let Some(t) = guard.take() {
                tracing::info!(
                    target: "grok_app::serve",
                    pid = t.pid,
                    bind = %t.bind,
                    secret = %mask_secret(&t.secret),
                    "stopping agent serve"
                );
                if pid_alive(t.pid) {
                    kill_tracked(t.pid, t.pgid);
                }
            }
        }
        // Brief settle so port probe reflects closed.
        std::thread::sleep(Duration::from_millis(150));
        Ok(collect_status_sync(false))
    })
    .await
    .map_err(|e| e.to_string())?
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mask_secret_short_and_long() {
        assert_eq!(mask_secret(""), "");
        assert_eq!(mask_secret("ab"), "••••");
        assert_eq!(mask_secret("super-secret-token"), "••••oken");
        assert_eq!(mask_secret("abcd"), "••••");
        assert_eq!(mask_secret("abcde"), "••••bcde");
    }

    #[test]
    fn secret_last4_works() {
        assert_eq!(secret_last4(""), "");
        assert_eq!(secret_last4("xy"), "xy");
        assert_eq!(secret_last4("super-secret-token"), "oken");
    }

    #[test]
    fn generate_secret_is_long_url_safe() {
        let s = generate_serve_secret();
        assert!(s.len() >= 32, "len {}", s.len());
        assert!(!s.contains('+') && !s.contains('/') && !s.contains('='));
    }

    #[test]
    fn normalize_bind_default_and_valid() {
        assert_eq!(normalize_bind(None).unwrap(), DEFAULT_SERVE_BIND);
        assert_eq!(normalize_bind(Some("")).unwrap(), DEFAULT_SERVE_BIND);
        assert_eq!(
            normalize_bind(Some("127.0.0.1:3000")).unwrap(),
            "127.0.0.1:3000"
        );
        assert!(normalize_bind(Some("http://evil")).is_err());
        assert!(normalize_bind(Some("not-a-bind")).is_err());
    }

    #[test]
    fn build_connection_url_shape() {
        let url = build_connection_url("127.0.0.1:2419", "tokensecret99");
        assert_eq!(
            url,
            "ws://127.0.0.1:2419/ws?server-key=tokensecret99"
        );
        let masked = build_connection_url_masked("127.0.0.1:2419", "tokensecret99");
        assert!(masked.contains("••••et99"));
        assert!(!masked.contains("tokensecret99"));
    }

    #[test]
    fn parse_serve_help_requires_bind_and_secret() {
        let ok_help = r#"
Run the agent as a WebSocket server
Options:
  --bind <BIND>      Address for the server to listen on
  --secret <SECRET>  Secret token for client authentication
"#;
        assert!(parse_serve_help_supports(ok_help, "", true));
        assert!(!parse_serve_help_supports(ok_help, "", false));
        assert!(!parse_serve_help_supports("unknown command", "", true));
        assert!(!parse_serve_help_supports("--bind only", "", true));
    }

    #[test]
    fn derive_state_matrix() {
        let (s, m) = derive_serve_state(false, false, false, false, None);
        assert_eq!(s, "error");
        assert!(m.unwrap().contains("not found"));

        let (s, m) = derive_serve_state(true, false, false, false, None);
        assert_eq!(s, "unsupported");
        assert!(m.unwrap().contains("agent serve"));

        let (s, _) = derive_serve_state(true, true, true, false, None);
        assert_eq!(s, "running");

        let (s, _) = derive_serve_state(true, true, false, true, None);
        assert_eq!(s, "running");

        let (s, _) = derive_serve_state(true, true, false, false, None);
        assert_eq!(s, "stopped");
    }

    #[test]
    fn status_dto_serde_omits_full_secret_fields_when_none() {
        let dto = ServeStatusDto {
            state: "stopped".into(),
            bind: DEFAULT_SERVE_BIND.into(),
            secret_masked: None,
            secret_last4: None,
            connection_url: None,
            pid: None,
            tracked_pid: None,
            port_open: false,
            cli_found: true,
            cli_supports_serve: true,
            message: None,
        };
        let v = serde_json::to_value(&dto).unwrap();
        assert!(v.get("secretMasked").is_none() || v.get("secretMasked").unwrap().is_null());
        assert!(v.get("connectionUrl").is_none() || v.get("connectionUrl").unwrap().is_null());
        // Never a raw "secret" field.
        assert!(v.get("secret").is_none());
    }
}
